routes/web.php
        Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
        //----------------Verification Email--------------
        Route::middleware('verifacition')->group(function (){
            Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
                ->name('verification');
            Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
                ->name('verification');
        });
    });
    Route::middleware('auth')->group(function (){
//        Route::get('/',[\App\Http\Controllers\User\HomeController::class, 'index'])->name('index');
        Route::group([
            'as' => 'declaration.'
        ],function (){
//            Route::get('/',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyself'])->name('myself');
            Route::post('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPost'])->name('myself');
            Route::get('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfEdit'])->name('myself.edit');
            Route::post('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPostEdit'])->name('myself.edit');
            Route::get('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeople'])->name('otherpeople');
            Route::post('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePost'])->name('otherpeople');
            Route::get('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeopleEdit'])->name('otherpeople.edit');
            Route::post('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePostEdit'])->name('otherpeople.edit');
            Route::get('/declaration-show-detail/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationShowDetail'])->name('show-detail');
            Route::delete('/declaration-delete',[\App\Http\Controllers\User\DeclarationController::class, 'destroy'])->name('destroy');
            Route::post('/declaration-redirect',[\App\Http\Controllers\User\DeclarationController::class, 'redirect'])->name('redirect');

        });
        Route::resource('vaccination', '\App\Http\Controllers\User\VaccinationController');
        Route::group([
            'as' => 'vaccination.'
        ],function (){
            Route::get('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOther'])->name('create-other');
            Route::post('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOtherPost'])->name('create-other');
            Route::post('/vaccination-redirect',[\App\Http\Controllers\User\VaccinationController::class, 'redirect'])->name('redirect');
            Route::get('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'editOther'])->name('edit-other');
            Route::post('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'updateOtherPost'])->name('update-other');
            Route::delete('/vaccination-delete',[\App\Http\Controllers\User\VaccinationController::class, 'destroy'])->name('destroy');
        });
        Route::resource('quarantine-athome', '\App\Http\Controllers\User\QuarantineAthomeController');
        Route::group([
            'as' => 'quarantine-athome.'
        ],function (){
            Route::get('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'createOther'])->name('create-other');
            Route::post('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'storeOther'])->name('store-other');
            Route::post('/quarantine-athome-redirect',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'redirect'])->name('redirect');
            Route::get('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'editOther'])->name('edit-other');
            Route::post('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'updateOther'])->name('update-other');
            Route::delete('/quarantine-athome-delete',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'destroy'])->name('destroy');
        });
        Route::resource('health_monitoring', '\App\Http\Controllers\User\HealthMonitoringController');
        Route::post("health_monitoring/update",[\App\Http\Controllers\User\HealthMonitoringController::class, "update"])->name("health_monitoring.update");
        Route::resource('destination', '\App\Http\Controllers\User\DestinationController');
        Route::get('/refresh_captcha', [\App\Http\Controllers\User\DeclarationController::class, 'refreshCaptcha'])->name('refresh_captcha');
        Route::get('/logout',[\App\Http\Controllers\User\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

//-----------------Medical Station----------------
Route::group([
    'as' => 'medical_station.',
    'prefix' => 'medical-station'
    ],function (){
        Route::group([
            'as' => 'auth.'
        ],function (){
            Route::get('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'index'])->name('login');
            Route::post('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'login'])->name('login');
//            Route::get('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'index'])->name('register');
//            Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
            //----------------Verification Email--------------
//            Route::middleware('verifacition')->group(function (){
//                Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
//                    ->name('verification');
//                Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
//                    ->name('verification');
//            });
        });
        Route::middleware('medicalstation')->group(function (){
            Route::get("dashboard",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            Route::get("/",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            // Management Health Declaration
            Route::get("mng-declaration", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "index"])->name("declaration.index");
            Route::get("mng-declaration/{iddeclaration}", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "declarationDetail"])->name("declaration.detail");
            Route::get("export", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "export"])->name("declaration.export");
            // Management Object Register Vaccination
            Route::get("mng-register-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "index"])->name("vaccination.index");
            Route::get("mng-register-vaccination/{idvaccination}", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "vaccinationDetail"])->name("vaccination.detail");
            Route::get("export-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "export"])->name("vaccination.export");

            Route::get("mng-quantine-athome", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "index"])->name("quanrantine_athome.index");
            Route::get("mng-quantine-athome/{idquarantine}", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "quaratineDetail"])->name("quanrantine_athome.detail");
            Route::post("mng-update_medical-staff", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "updateMedicalStaff"])->name("quanrantine_athome.update_medical_staff");
            Route::post("mng-update_status_quarantine", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "updateStatusQuarantine"])->name("quanrantine_athome.update_status_quarantine");
            Route::get("mng-update_status_confirm", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "confirmmm"])->name("quanrantine_athome.confirmmm");
            Route::get("export-quantine-athome", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "export"])->name("quanrantine_athome.export");

//            Manage Medical Staff
            Route::resource("medical-staff", \App\Http\Controllers\MedicalStation\MNGMedicalStaffController::class);
            Route::resource("medical-station", \App\Http\Controllers\MedicalStation\MNGMedicalStationController::class);
//            Manage News
            Route::resource("news", \App\Http\Controllers\MedicalStation\MNGNewsController::class);
//            Manage Notification
            Route::resource("notification", \App\Http\Controllers\MedicalStation\MNGNotificationController::class);

app/Http/Controllers/User/DestinationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateScheduleRequest;
use App\Models\District;
use App\Models\Province;
use App\Models\Schedule;
use App\Models\Ward;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Nette\Schema\Schema;

class DestinationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $schedules = Schedule::with("province")->with("district")->with("ward")->orderBy("from_date", "DESC");
        $schedules->where("name","LIKE", "%".$request->name."%")->where("user_id", Auth::id());
        $from_date = $request->from_date;
        $to_date = $request->to_date;
        if ($from_date != null){
            $schedules->whereDate("from_date",">=", $from_date);
        }
        if ($to_date != null){
            $schedules->whereDate("to_date","<=", $to_date);
        }
        $name = $request->name;
        $data["name"] = $name;
        $data["from_date"] = $from_date;
        $data["to_date"] = $to_date;
        $data['schedules'] =$schedules->paginate(5);
        return view("user.pages.destination.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $data['provinces'] = Province::getProvince();
        return view("user.pages.destination.create", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(CreateScheduleRequest $request)
    {
        $request->validated();
        if($request->province_id == 0 || $request->district_id == 0 || $request->ward_id == 0)
        {
            session()->flash("error", "Yêu cầu nhập địa chỉ");
        } else {
            $result = Schedule::create($request);
            if ($result == true){
                session()->flash("success", "Thêm địa chỉ thành công");
                return redirect()->route('user.destination.index');
            } else {
                session()->flash("error", "Thêm địa chỉ thất bại");
                return back();
            }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $schedule = Schedule::find($id);
        $data['schedule'] = $schedule;
        $districts = District::where('_province_id', $schedule->province_id)->get();
        $wards = Ward::where('_district_id', $schedule->district_id)->get();
        $data['provinces'] = Province::getProvince();
        $data['districts'] = $districts;
        $data['wards'] = $wards;
        return view("user.pages.destination.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateScheduleRequest $request, $id)
    {
        $request->validated();
        $result = Schedule::updates($id, $request);
        if ($result == true){
            session()->flash("success", "Cập nhật địa chỉ thành công");
            return redirect()->route('user.destination.index');
        } else {
            session()->flash("error", "Cập nhật địa chỉ thất bại");
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/pages/destination/create.blade.php
@extends('user.layout.main',['title' => 'Thêm nhật ký điểm đến'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Trang chủ</li>
                    <li class="breadcrumb-item">Quản lý điểm đến</li>
                    <li class="breadcrumb-item active" aria-current="page">Thêm mới điểm đến</li>
                </ol>
            </nav>
            @include("user.shared._button-back")
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Thêm nhật ký điểm đến</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Thông tin địa điểm</b>
                                </div>
                            </div>
                        </div>
                    </div>

                    <form action="{{ route('user.destination.store') }}" class="p-5" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="name" class="form-label">Tên địa điểm<span
                                        class="obligatory">(*)</span></label>
                                <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}" placeholder="Nhập tên địa điểm">
                            </div>
                            <div class="mb-3 col-6"></div>
                            <div class="mb-3 col-6">
                                <label for="address" class="form-label">Thời gian đến<span
                                        class="obligatory">(*)</span></label>
                                <input type="datetime-local" class="form-control" name="from_date" value="{{ old('from_date', date('Y-m-d ; hh:mm')) }}" id="from_date" placeholder="dd/mm/yyy hh:mm">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="address" class="form-label">Thời gian đi<span
                                        class="obligatory">(*)</span></label>
                                <input type="datetime-local" class="form-control" name="to_date" value="{{ old('to_date', date('Y-m-d ; hh:mm')) }}" id="to_date" placeholder="dd/mm/yyy hh:mm">
                            </div>
                        </div>

                        @include('user.pages.location')
                        <div class="mb-3 ">
                            <label for="address" class="form-label">Số nhà, phố, tổ dân phố/thôn/đội <span
                                    class="obligatory">(*)</span></label>
                            <input type="text" class="form-control" name="address" value="{{ old("address") }}" id="address" placeholder="Nhập Số nhà, phố, tổ dân phố/thôn/đội ">
                        </div>
                        <div class="mb-3 ">
                            <label for="address" class="form-label">Ghi chú</label>
                            <textarea class="form-control" name="note" value="{{ old("note") }}" id="note" cols="" rows="5" placeholder="Ghi chú địa điểm"></textarea>
                        </div>
                        <div class="text-center">
                            <a href="{{ route("user.destination.index") }}" class="btn btn-info text-white">Quay lại</a>
                            <button type="submit" class="btn btn-primary btn-submit btn-success">Xác nhận</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/pages/destination/index.blade.php
@extends('user.layout.main',['title' => 'Quản lý địa điểm'])
@section('content')
    <div class="content">
        <div class="container-fluid">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Trang chủ</li>
                    <li class="breadcrumb-item active" aria-current="page">Quản lý điểm đến</li>
                </ol>
            </nav>
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Quản lý địa điểm</h1>
                </div>
                <div class="declaration-form">
                    <div class="container">
                        <div class="row my-3">
                            <div class="right-option col-12">
                                <form action="" class="row" method="get">
                                    <div class="mb-3 col-4">
                                        <label for="name" class="form-label">Tên địa điểm<span
                                                class="obligatory">(*)</span></label>
                                        <input type="text" name="name" class="form-control" id="name" value="{{ $name }}" placeholder="Nhập tên địa điểm">
                                    </div>
                                    <div class="mb-3 col-3">
                                        <label for="from_date" class="form-label">Từ ngày:<span
                                                class="obligatory">(*)</span></label>
                                        <input type="date" name="from_date" class="form-control" id="from_date" value="{{ $from_date }}" >
                                    </div>
                                    <div class="mb-3 col-3">
                                        <label for="name" class="form-label">Đến ngày:<span
                                                class="obligatory">(*)</span></label>
                                        <input type="date" name="to_date" class="form-control" id="to_date" value="{{ $to_date }}">
                                    </div>
                                    <div class="mb-3 col-2">
                                        <label for="name" class="form-label">.</label>
                                        <input type="submit" class="form-control btn btn-md btn-primary" value="Tìm kiếm">
                                    </div>
                                    <div class="col-6 d-flex">
                                        <a href="{{ route('user.destination.create') }}" style="font-weight: 600" class="btn btn-primary" tabindex="0" ><i  class="anticon anticon-plus ng-star-inserted" style="display: inline-block;"><svg viewBox="64 64 896 896" fill="currentColor" width="1em" height="1em" data-icon="plus" aria-hidden="true"><defs><style></style></defs><path d="M482 152h60q8 0 8 8v704q0 8-8 8h-60q-8 0-8-8V160q0-8 8-8z"></path><path d="M176 474h672q8 0 8 8v60q0 8-8 8H176q-8 0-8-8v-60q0-8 8-8z"></path></svg></i><span> Thêm mới địa điểm </span></a>
                                        <a href="{{ route('user.destination.index') }}" style="font-weight: 600" class="btn btn-info text-white ms-3" tabindex="0" ><i class="fas fa-retweet"></i><span> Làm mới </span></a>
                                    </div>
                                </form>

                            </div>
                        </div>
                        <table class="table table-bordered table-hover table-striped inlineEditTable">
                            <thead class="noselect">
                            <tr style="height: 57.5px;">
                                <th scope="col" >STT</th>
                                <th scope="col" >Tên địa điểm</th>
                                <th scope="col" >Thời gian đến</th>
                                <th scope="col">Thời gian đi</th>
                                <th scope="col">Ghi chú</th>
                                <th scope="col">Thao tác</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($schedules as $key => $schedule)
                                    <tr>
                                        <td style=" text-align: center;">{{ $key + 1 }}</td>
                                        <td >
                                            <p><b>{{ $schedule->name }}</b></p>
                                            <p>{{ $schedule->address.", ".$schedule->ward->_name.", ".$schedule->district->_name.", ".$schedule->province->_name }}</p>
                                        </td>
                                        <td >{{ date('d-m-Y H:i:s', strtotime($schedule->from_date)) }}</td>
                                        <td >{{ date('d-m-Y H:i:s', strtotime($schedule->to_date)) }}</td>
                                        <td>{{ $schedule->note }}</td>
                                        <td class="text-center" >
{{--                                            <a href="{{ route('user.destination.index') }}" class="fs-5 text-decoration-none text-success" alt="Xem">--}}
{{--                                                <i class="fas fa-eye"></i>--}}
{{--                                            </a>--}}
                                            <a href="{{ route('user.destination.edit', $schedule->id) }}" class="fs-5 text-decoration-none" alt="Sửa">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a href="{{ route('user.destination.index') }}" class="fs-5 text-decoration-none text-danger" alt="Xóa">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div>{{ $schedules->links() }}</div>
                    </div>
                </div>

            </div>
            <div class="number-pages card-footer clearfix" >
{{--                {{ $schedules->links() }}--}}
            </div>
        </div>
    </div>

@endsection