routes/web.php
    Route::get('/news/{id}',[\App\Http\Controllers\User\HomeController::class, 'newsDetail'])->name('news_detail');
    //---------------- User Auth --------------
    Route::group([
        'as' => 'auth.'
    ],function (){
        Route::get('/login',[\App\Http\Controllers\User\Auth\LoginController::class, 'index'])->name('login');
        Route::post('/login',[\App\Http\Controllers\User\Auth\LoginController::class, 'login'])->name('login');
        Route::get('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'index'])->name('register');
        Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
        //----------------Verification Email--------------
        Route::middleware('verifacition')->group(function (){
            Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
                ->name('verification');
            Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
                ->name('verification');
        });
    });
    Route::middleware('auth')->group(function (){
//        Route::get('/',[\App\Http\Controllers\User\HomeController::class, 'index'])->name('index');
        Route::group([
            'as' => 'declaration.'
        ],function (){
//            Route::get('/',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyself'])->name('myself');
            Route::post('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPost'])->name('myself');
            Route::get('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfEdit'])->name('myself.edit');
            Route::post('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPostEdit'])->name('myself.edit');
            Route::get('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeople'])->name('otherpeople');
            Route::post('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePost'])->name('otherpeople');
            Route::get('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeopleEdit'])->name('otherpeople.edit');
            Route::post('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePostEdit'])->name('otherpeople.edit');
            Route::get('/declaration-show-detail/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationShowDetail'])->name('show-detail');
            Route::delete('/declaration-delete',[\App\Http\Controllers\User\DeclarationController::class, 'destroy'])->name('destroy');
            Route::post('/declaration-redirect',[\App\Http\Controllers\User\DeclarationController::class, 'redirect'])->name('redirect');

        });
        Route::resource('vaccination', '\App\Http\Controllers\User\VaccinationController');
        Route::group([
            'as' => 'vaccination.'
        ],function (){
            Route::get('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOther'])->name('create-other');
            Route::post('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOtherPost'])->name('create-other');
            Route::post('/vaccination-redirect',[\App\Http\Controllers\User\VaccinationController::class, 'redirect'])->name('redirect');
            Route::get('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'editOther'])->name('edit-other');
            Route::post('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'updateOtherPost'])->name('update-other');
            Route::delete('/vaccination-delete',[\App\Http\Controllers\User\VaccinationController::class, 'destroy'])->name('destroy');
        });
        Route::resource('quarantine-athome', '\App\Http\Controllers\User\QuarantineAthomeController');
        Route::group([
            'as' => 'quarantine-athome.'
        ],function (){
            Route::get('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'createOther'])->name('create-other');
            Route::post('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'storeOther'])->name('store-other');
            Route::post('/quarantine-athome-redirect',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'redirect'])->name('redirect');
            Route::get('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'editOther'])->name('edit-other');
            Route::post('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'updateOther'])->name('update-other');
            Route::delete('/quarantine-athome-delete',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'destroy'])->name('destroy');
        });
        Route::resource('health_monitoring', '\App\Http\Controllers\User\HealthMonitoringController');
        Route::post("health_monitoring/update",[\App\Http\Controllers\User\HealthMonitoringController::class, "update"])->name("health_monitoring.update");
        Route::resource('destination', '\App\Http\Controllers\User\DestinationController');
        Route::get('/refresh_captcha', [\App\Http\Controllers\User\DeclarationController::class, 'refreshCaptcha'])->name('refresh_captcha');
        Route::get('/logout',[\App\Http\Controllers\User\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

//-----------------Medical Station----------------
Route::group([
    'as' => 'medical_station.',
    'prefix' => 'medical-station'
    ],function (){
        Route::group([
            'as' => 'auth.'
        ],function (){
            Route::get('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'index'])->name('login');
            Route::post('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'login'])->name('login');
//            Route::get('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'index'])->name('register');
//            Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
            //----------------Verification Email--------------
//            Route::middleware('verifacition')->group(function (){
//                Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
//                    ->name('verification');
//                Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
//                    ->name('verification');
//            });
        });
        Route::middleware('medicalstation')->group(function (){
            Route::get("dashboard",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            Route::get("/",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            // Management Health Declaration
            Route::get("mng-declaration", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "index"])->name("declaration.index");
            Route::get("mng-declaration/{iddeclaration}", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "declarationDetail"])->name("declaration.detail");
            Route::get("export", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "export"])->name("declaration.export");
            // Management Object Register Vaccination
            Route::get("mng-register-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "index"])->name("vaccination.index");
            Route::get("mng-register-vaccination/{idvaccination}", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "vaccinationDetail"])->name("vaccination.detail");
            Route::get("export-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "export"])->name("vaccination.export");

            Route::get("mng-quantine-athome", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "index"])->name("quanrantine_athome.index");
            Route::get("mng-quantine-athome/{idquarantine}", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "quaratineDetail"])->name("quanrantine_athome.detail");
            Route::post("mng-update_medical-staff", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "updateMedicalStaff"])->name("quanrantine_athome.update_medical_staff");
            Route::post("mng-update_status_quarantine", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "updateStatusQuarantine"])->name("quanrantine_athome.update_status_quarantine");
            Route::get("mng-update_status_confirm", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "confirmmm"])->name("quanrantine_athome.confirmmm");
            Route::get("export-quantine-athome", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "export"])->name("quanrantine_athome.export");

//            Manage Medical Staff

resources/views/user/pages/vaccination/create-detail.blade.php
<div class="row py-3">
    @include("user.pages.shared._guardian")
    <div class=" col-md-4">
        <label for="medical_station_id" class="form-label">Đăng kí mũi tiêm thứ <span
                class="obligatory">(*)</span></label>
        <select name="injection" id="injection" class="form-control form-select">
            <option value="1" {{ old("injection") == 1 ? "selected" : "" }}>Mũi tiêm thứ nhất</option>
            <option value="2" {{ old("injection") == 2 ? "selected" : "" }}>Mũi tiếp tiếp theo</option>
        </select>
    </div>
    <div class=" col-md-4">
        <label for="vaccin_id" class="form-label">Loại vacxin đã tiêm<span
                class="obligatory"></span></label>
        <select name="vaccin_id" id="vaccin_id" class="form-control form-select">
            <option value="0">Chọn loại</option>
            @foreach($vaccines as $key => $vaccine)
                <option value="{{ $vaccine->id }}" {{ $vaccine->id == old("vaccin_id") ? "selected" : "" }}>{{ $vaccine->name }}</option>
            @endforeach
        </select>
    </div>
    <div class=" col-4">
        <label for="last_injection" class="form-label">Thời gian mũi tiêm gần nhất <span
                class="obligatory"></span></label>
        <input type="date" name="last_injection" class="form-control" id="last_injection" value="{{ old('last_injection') }}" placeholder="dd/mm/YYY">
    </div>
</div>
<table class="table table-bordered">
    <thead class="table-light">
    <tr>
        <th>Bệnh nền</th>
        <th class="text-bold">Có</th>
        <th class="text-bold">Không</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="col-10">
            1. Tiền sử phản vệ từ độ 2 trở lên <span class="obligatory ">(*)</span>
        </td>
        <td class="col-1">
            <input class="form-check-input" type="radio" name="tsphanve"  id="tsphanve" value="1">
        </td>
        <td class="col-1">
            <input class="form-check-input" type="radio" name="tsphanve" id="tsphanve" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            2. Tiền sử bị COVID-19 trong vòng 6 tháng <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tscovid" id="tscovid" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tscovid" id="tscovid" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            3. Tiền sử suy giảm miễn dịch, ung thư giai đoạn cuối, cắt lách, xơ gan mất bù ... <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tssuygiammd" id="tssuygiammd" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tssuygiammd" id="tssuygiammd" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            4. Bệnh cấp tính <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="benhcaptinh" id="benhcaptinh" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="benhcaptinh" id="benhcaptinh" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            5. Tiền sử bệnh mạn tính, đang tiến triển <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tsmantinh" id="tsmantinh" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="tsmantinh" id="tsmantinh" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            6. Độ tuổi: ≥65 tuổi <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="age" id="age" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="age" id="age" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            7. Đang mang thai, phụ nữ đang nuôi con bằng sữa mẹn <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="mangthai" id="mangthai" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="mangthai" id="mangthai" checked value="0">
        </td>
    </tr>

    </tbody>
</table>
<div class="mb-3 ">
    <label for="address" class="form-label">Ghi chú (Tiền sử dị ứng với các dị nguyên khác)</label>
    <textarea class="form-control" name="note" id="note" cols="" rows="5"></textarea>
</div>
<div class="form-group{{ $errors->has('captcha') ? ' has-error' : '' }}">
    <label for="password" class="col-md-4 control-label py-2">Mã bảo mật<span
            class="obligatory">(*)</span></label>
    <div class="col-md-6 ">
        <div class="row">
            <div class="captcha col-sm-4">
                <span>{!! captcha_img() !!}</span>
                <button type="button" class="btn btn-success btn-refresh"><i class="fa fa-refresh"></i></button>
            </div>
            <div class="col-sm-8">
                <input id="captcha" type="text" class="form-control" placeholder="Nhập mã bảo mật" name="captcha">

            </div>

        </div>
        @if ($errors->has('captcha'))
            <span class="help-block">
          <strong>{{ $errors->first('captcha') }}</strong>
      </span>
        @endif
    </div>
</div>
<ul class="py-4">
    <p class="text-danger fw-bold">Lưu ý</p>
    <li class="text-danger">Việc đăng ký thông tin hoàn toàn bảo mật và phục vụ cho chiến dịch tiêm chủng Vắc xin COVID - 19</li>
    <li class="text-danger">Bằng việc nhấn nút "Xác nhận", bạn hoàn toàn hiểu và đồng ý chịu trách nhiệm với các thông tin đã cung cấp.</li>
    <li class="text-danger">Nếu bạn dưới 18 tuổi, vui lòng nhập số điện thoại của người giám hộ để tra cứu</li>
</ul>

<div class="text-center">
    <a href="{{ route("user.vaccination.index") }}" class="btn btn-info text-white">Quay lại</a>
    <button type="submit" class="btn btn-primary btn-success">Xác nhận đăng ký</button>
</div>
@push('custom-scripts')
    <script type="text/javascript">
        $(document).ready(function(){
            let injection = $("#injection");
            let vaccin_id = $("#vaccin_id");
            let last_injection = $("#last_injection");
            // vaccin_id.hide();
            // last_injection.hide();
            // vaccin_id.attr('disabled', true);
            // last_injection.attr('disabled', true);
            // console.log(injection.value);
            if (injection.val() == 1){
                vaccin_id.hide();
                last_injection.hide();
                // vaccin_id.attr('disabled', true);
                // last_injection.attr('disabled', true);
                // $('#vaccin_id option[value="0"]').attr('selected', true);
                // last_injection.html(`<input type="date" name="last_injection" class="form-control" value="NULL" id="last_injection" placeholder="dd/mm/YYY">`);
            } else {
                vaccin_id.show();
                last_injection.show();
                // $("#vaccin_id").attr('disabled', false);
                // $("#last_injection").attr('disabled', false);
                // $('#vaccin_id option[value="0"]').attr('selected', false);
            }
            injection.change(function (e){
                if(this.value == 1){
                    // console.log(injection.val());
                    vaccin_id.hide();
                    last_injection.hide();
                    // vaccin_id.attr('disabled', true);
                    // last_injection.attr('disabled', true);
                    // $('#vaccin_id option[value="0"]').attr('selected', true);
                    // last_injection.html(`<input type="date" name="last_injection" class="form-control" value="NULL" id="last_injection" placeholder="dd/mm/YYY">`);
                } else {
                    vaccin_id.show();
                    last_injection.show();
                    // $("#vaccin_id").attr('disabled', false);
                    // $("#last_injection").attr('disabled', false);
                    // $('#vaccin_id option[value="0"]').attr('selected', false);
                }
            })
        });
    </script>
@endpush

resources/views/user/pages/vaccination/create-other.blade.php
@extends('user.layout.main',['title' => 'Đăng ký tiêm vaccin'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Đăng ký tiêm vacxin</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Thông tin đăng ký cho người thân</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route("user.vaccination.create-other") }}" class="p-5" method="POST">
                        @csrf
                        @include("user.pages.shared._other-user")
                        @include('user.pages.vaccination.create-detail')
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $(".btn-refresh").click(function(){
                $.ajax({
                    type:'GET',
                    url:'{{ route('user.refresh_captcha') }}',
                    success:function(data){
                        $(".captcha span").html(data.captcha);
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function(){
                $("#medical_station_id").attr('disabled', true);
                $("#ward").change(function(){
                    console.log($(this).val());
                    let id = $(this).val();
                    $.ajax({
                        url: '{{ route('medical-station.get') }}',
                        method:'POST',
                        data: {
                            id : id,
                            _token: '{{csrf_token()}}'
                        },
                        success: function (responsive){
                            console.log(responsive);
                            let medical_station_id = $("#medical_station_id");
                            medical_station_id.html(`<option value="0">-- Chọn trạm y tế --</option>`);
                            medical_station_id.attr('disabled', false);
                            $.each( responsive, function( key, value ) {
                                $("#medical_station_id").append(`<option value="${value['id']}">  ${value['name']} </option>`);
                            });

                        }
                    });
                });
            });
        </script>
    @endpush
@endsection

resources/views/user/pages/vaccination/create.blade.php
@extends('user.layout.main',['title' => 'Đăng ký tiêm vaccin'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Đăng ký tiêm vacxin</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Thông tin đăng ký cho bản thân</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route("user.vaccination.store") }}" class="p-5" method="POST">
                        @csrf
                        @include('user.pages.vaccination.create-detail')
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $(".btn-refresh").click(function(){
                $.ajax({
                    type:'GET',
                    url:'{{ route('user.refresh_captcha') }}',
                    success:function(data){
                        $(".captcha span").html(data.captcha);
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function(){
                $("#medical_station_id").attr('disabled', true);
                $("#ward").change(function(){
                    console.log($(this).val());
                    let id = $(this).val();
                    $.ajax({
                        url: '{{ route('medical-station.get') }}',
                        method:'POST',
                        data: {
                            id : id,
                            _token: '{{csrf_token()}}'
                        },
                        success: function (responsive){
                            console.log(responsive);
                            let medical_station_id = $("#medical_station_id");
                            medical_station_id.html(`<option value="0">-- Chọn trạm y tế --</option>`);
                            medical_station_id.attr('disabled', false);
                            $.each( responsive, function( key, value ) {
                                $("#medical_station_id").append(`<option value="${value['id']}">  ${value['name']} </option>`);
                            });

                        }
                    });
                });
            });
        </script>
    @endpush
@endsection

resources/views/user/pages/vaccination/edit.blade.php
@extends('user.layout.main',['title' => 'Đăng ký tiêm vaccin'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Cập nhật tiêm vacxin</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Cập nhật thông tin đăng ký cho bản thân</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route("user.vaccination.update", $object->id) }}" class="p-5" method="POST">
                        @csrf
                        {{ method_field("PUT") }}
                        @include('user.pages.vaccination.edit-detail')
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $(".btn-refresh").click(function(){
                $.ajax({
                    type:'GET',
                    url:'{{ route('user.refresh_captcha') }}',
                    success:function(data){
                        $(".captcha span").html(data.captcha);
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function(){
                $("#medical_station_id").attr('disabled', true);
                $("#ward").change(function(){
                    console.log($(this).val());
                    let id = $(this).val();
                    $.ajax({
                        url: '{{ route('medical-station.get') }}',
                        method:'POST',
                        data: {
                            id : id,
                            _token: '{{csrf_token()}}'
                        },
                        success: function (responsive){
                            console.log(responsive);
                            let medical_station_id = $("#medical_station_id");
                            medical_station_id.html(`<option value="0">-- Chọn trạm y tế --</option>`);
                            medical_station_id.attr('disabled', false);
                            $.each( responsive, function( key, value ) {
                                $("#medical_station_id").append(`<option value="${value['id']}">  ${value['name']} </option>`);
                            });

                        }
                    });
                });
            });
        </script>
    @endpush
@endsection