routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/district', [\App\Http\Controllers\LocationController::class, 'district'])->name('district.get');
Route::post('/ward', [\App\Http\Controllers\LocationController::class, 'ward'])->name('ward.get');
Route::post('/medical-station', [\App\Http\Controllers\LocationController::class, 'medicalStation'])->name('medical-station.get');

//-----------------User----------------
Route::group([
    'as' => 'user.'
],function (){
    Route::get('/',[\App\Http\Controllers\User\HomeController::class, 'index'])->name('home');
    Route::get('/news/{id}',[\App\Http\Controllers\User\HomeController::class, 'newsDetail'])->name('news_detail');
    //---------------- User Auth --------------
    Route::group([
        'as' => 'auth.'
    ],function (){
        Route::get('/login',[\App\Http\Controllers\User\Auth\LoginController::class, 'index'])->name('login');
        Route::post('/login',[\App\Http\Controllers\User\Auth\LoginController::class, 'login'])->name('login');
        Route::get('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'index'])->name('register');
        Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
        //----------------Verification Email--------------
        Route::middleware('verifacition')->group(function (){
            Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
                ->name('verification');
            Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
                ->name('verification');
        });
    });
    Route::middleware('auth')->group(function (){
//        Route::get('/',[\App\Http\Controllers\User\HomeController::class, 'index'])->name('index');
        Route::group([
            'as' => 'declaration.'
        ],function (){
//            Route::get('/',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration',[\App\Http\Controllers\User\DeclarationController::class, 'index'])->name('index');
            Route::get('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyself'])->name('myself');
            Route::post('/declaration-myself',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPost'])->name('myself');
            Route::get('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfEdit'])->name('myself.edit');
            Route::post('/declaration-myself-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationMyselfPostEdit'])->name('myself.edit');
            Route::get('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeople'])->name('otherpeople');
            Route::post('/declaration-other-people',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePost'])->name('otherpeople');
            Route::get('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeopleEdit'])->name('otherpeople.edit');
            Route::post('/declaration-other-people-edit/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationOtherPeoplePostEdit'])->name('otherpeople.edit');
            Route::get('/declaration-show-detail/{id}',[\App\Http\Controllers\User\DeclarationController::class, 'declarationShowDetail'])->name('show-detail');
            Route::delete('/declaration-delete',[\App\Http\Controllers\User\DeclarationController::class, 'destroy'])->name('destroy');
            Route::post('/declaration-redirect',[\App\Http\Controllers\User\DeclarationController::class, 'redirect'])->name('redirect');

        });
        Route::resource('vaccination', '\App\Http\Controllers\User\VaccinationController');
        Route::group([
            'as' => 'vaccination.'
        ],function (){
            Route::get('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOther'])->name('create-other');
            Route::post('/vaccination-other',[\App\Http\Controllers\User\VaccinationController::class, 'createOtherPost'])->name('create-other');
            Route::post('/vaccination-redirect',[\App\Http\Controllers\User\VaccinationController::class, 'redirect'])->name('redirect');
            Route::get('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'editOther'])->name('edit-other');
            Route::post('/vaccination-other-edit/{id}',[\App\Http\Controllers\User\VaccinationController::class, 'updateOtherPost'])->name('update-other');
            Route::delete('/vaccination-delete',[\App\Http\Controllers\User\VaccinationController::class, 'destroy'])->name('destroy');
        });
        Route::resource('quarantine-athome', '\App\Http\Controllers\User\QuarantineAthomeController');
        Route::group([
            'as' => 'quarantine-athome.'
        ],function (){
            Route::get('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'createOther'])->name('create-other');
            Route::post('/quarantine-athome-other',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'storeOther'])->name('store-other');
            Route::post('/quarantine-athome-redirect',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'redirect'])->name('redirect');
            Route::get('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'editOther'])->name('edit-other');
            Route::post('/quarantine-athome-other-edit/{id}',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'updateOther'])->name('update-other');
            Route::delete('/quarantine-athome-delete',[\App\Http\Controllers\User\QuarantineAthomeController::class, 'destroy'])->name('destroy');
        });
        Route::resource('health_monitoring', '\App\Http\Controllers\User\HealthMonitoringController');
        Route::post("health_monitoring/update",[\App\Http\Controllers\User\HealthMonitoringController::class, "update"])->name("health_monitoring.update");
        Route::resource('destination', '\App\Http\Controllers\User\DestinationController');
        Route::get('/refresh_captcha', [\App\Http\Controllers\User\DeclarationController::class, 'refreshCaptcha'])->name('refresh_captcha');
        Route::get('/logout',[\App\Http\Controllers\User\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

//-----------------Medical Station----------------
Route::group([
    'as' => 'medical_station.',
    'prefix' => 'medical-station'
    ],function (){
        Route::group([
            'as' => 'auth.'
        ],function (){
            Route::get('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'index'])->name('login');
            Route::post('login',[\App\Http\Controllers\MedicalStation\Auth\LoginController::class, 'login'])->name('login');
//            Route::get('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'index'])->name('register');
//            Route::post('/register',[\App\Http\Controllers\User\Auth\RegisterController::class, 'register'])->name('register');
            //----------------Verification Email--------------
//            Route::middleware('verifacition')->group(function (){
//                Route::get('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCode'])
//                    ->name('verification');
//                Route::post('/verification',[\App\Http\Controllers\User\Auth\RegisterController::class, 'verificationByCodePost'])
//                    ->name('verification');
//            });
        });
        Route::middleware('medicalstation')->group(function (){
            Route::get("dashboard",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            Route::get("/",[\App\Http\Controllers\MedicalStation\DashboardController::class, "index"])->name("dashboard.index");
            // Management Health Declaration
            Route::get("mng-declaration", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "index"])->name("declaration.index");
            Route::get("mng-declaration/{iddeclaration}", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "declarationDetail"])->name("declaration.detail");
            Route::get("export", [\App\Http\Controllers\MedicalStation\MNGDeclarationController::class, "export"])->name("declaration.export");
            // Management Object Register Vaccination
            Route::get("mng-register-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "index"])->name("vaccination.index");
            Route::get("mng-register-vaccination/{idvaccination}", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "vaccinationDetail"])->name("vaccination.detail");
            Route::get("export-vaccination", [\App\Http\Controllers\MedicalStation\MNGVaccinationController::class, "export"])->name("vaccination.export");

            Route::get("mng-quantine-athome", [\App\Http\Controllers\MedicalStation\MNGQuarantineAthomeController::class, "index"])->name("quanrantine_athome.index");

app/Http/Controllers/User/DeclarationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserOtherRequest;
use App\Models\District;
use App\Models\HealthDeclaration;
use App\Models\MedicalStation;
use App\Models\Province;
use App\Models\Relationship;
use App\Models\User;
use App\Models\Ward;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DeclarationController extends Controller
{
    //
    public function index(){
        $user = HealthDeclaration::where('user_id', Auth::id())->select('object_id')->get()->toArray();
        $object_of_users = User::where("user_id", Auth::id())->whereNotIn('id', $user)->get();
//        dd($object_of_users);
        $data["object_of_users"] = $object_of_users;
        $healthDeclarations = HealthDeclaration::with('object')->where('user_id', Auth::id())->get();
        $data['healthDeclarations'] = $healthDeclarations;
        return view('user.pages.declaration.declaration', $data);
    }

    public function declarationMyself(){
        $data['provinces'] = Province::getProvince();
        return view('user.pages.declaration.declaration_myself', $data);
    }

    public function declarationMyselfPost(Request $request){
        $request->validate([
                'captcha' => 'required|captcha'
            ],
            [   'captcha.captcha'=>'Mã bảo mật chưa chính xác.',
                'captcha.required'=>'Yêu cầu nhập mã bảo mật.',
                ]);
        $idDeclaration = HealthDeclaration::declarationMyself($request);
        if($idDeclaration){
            session()->flash('success', "Tạo khai báo thành công.");
        }
        return redirect()->route('user.declaration.show-detail', $idDeclaration);
    }

    public function declarationMyselfEdit($id){
        $declaration = HealthDeclaration::where('object_id', $id)->first();
        $data['declaration'] = $declaration;
        return view('user.pages.declaration.declaration_myself_edit', $data);
    }

    public function declarationMyselfPostEdit($id, Request $request){
        $request->validate([
                'captcha' => 'required|captcha'
            ],
            [   'captcha.captcha'=>'Mã bảo mật chưa chính xác.',
                'captcha.required'=>'Yêu cầu nhập mã bảo mật.',
            ]);
        $idDeclaration = HealthDeclaration::declarationMyselfEdit($id, $request);
        if($idDeclaration){
            session()->flash('success', "Cập nhật khai báo thành công.");
        }
        return redirect()->route('user.declaration.show-detail', $idDeclaration);
    }

    public function declarationOtherPeople(){
        $relationship = Relationship::get();
        $data['relationship'] = $relationship;
        $data['provinces'] = Province::getProvince();
        return view('user.pages.declaration.declaration_other_people', $data);
    }

    public function declarationOtherPeoplePost(CreateUserOtherRequest $request){
        $request->validated();
        $contentEmail = 'Bạn vừa dùng mail này để khai báo y tế';
        $idDeclaration = HealthDeclaration::declarationOtherPeople($request, $contentEmail);
        if ($idDeclaration != false){
            session()->flash('success', "Tạo khai báo thành công.");
            return redirect()->route('user.declaration.show-detail', $idDeclaration);
        } else {
            return back()->withErrors([
                'message' => 'Kiểm tra lại thông tin khai báo.'
            ])->withInput();
        }

    }

    public function declarationOtherPeopleEdit($id){
        $object = User::find($id);
        $districts = District::where('_province_id', $object->province_id)->get();
        $wards = Ward::where('_district_id', $object->district_id)->get();
        $medical_stations = MedicalStation::where('ward_id', $object->ward_id)->get();
        $declaration = HealthDeclaration::where('object_id', $id)->first();
        $relationship = Relationship::get();
        $data['relationship'] = $relationship;
        $data['provinces'] = Province::getProvince();
        $data['districts'] = $districts;
        $data['wards'] = $wards;
        $data['medical_stations'] = $medical_stations;
        $data['declaration'] = $declaration;
        $data['object'] = $object;
        return view('user.pages.declaration.declaration_other_people_edit', $data);
    }

    public function declarationOtherPeoplePostEdit($id, CreateUserOtherRequest $request){
        $request->validated();
        $idDeclaration = HealthDeclaration::declarationOtherPeopleEdit($id, $request);
        if($idDeclaration != false){
            session()->flash('success', "Cập nhật khai báo thành công.");
            return redirect()->route('user.declaration.show-detail', $idDeclaration);
        } else {
            return back()->withErrors([
                'message' => 'Kiểm tra lại thông tin khai báo.'
            ])->withInput();
        }

    }

    public function declarationShowDetail($idDeclaration){
        $declaration = HealthDeclaration::with("object")->where("object_id", $idDeclaration)->first();
        $object = User::with("province")->with("district")->with("ward")->with("medicalStation")->find($idDeclaration);
        $data['declaration'] = $declaration;
//        dd($declaration);
        $data['object'] = $object;
        return view('user.pages.declaration.declaration_show_detail', $data);
    }

    public function redirect(Request $request){
        if(isset($request->object_of_user)){
            if($request->object_of_user == Auth::id()){
                return redirect()->route("user.declaration.myself");
            } else {
                HealthDeclaration::createWhenRedirect($request);
                return redirect()->route("user.declaration.otherpeople.edit", $request->object_of_user);
            }
        } else {
            return back()->withErrors([
                'message' => 'Vui lòng chọn đối tượng.'
            ])->withInput();
        }

    }

    public function destroy(Request $request){

        return HealthDeclaration::deleteDeclaration($request->id);
    }
    /**
     * Create a new controller instance.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function refreshCaptcha()
    {
        return response()->json(['captcha'=> captcha_img()]);
    }
}

resources/views/user/pages/declaration/declaration_detail.blade.php
<table class="table table-bordered">
    <thead class="table-light">
        <tr>
            <th>Dấu hiệu</th>
            <th class="text-bold">Có</th>
            <th class="text-bold">Không</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-10">
                Sốt <span class="obligatory ">(*)</span>
            </td>
            <td class="col-1">
                <input class="form-check-input" type="radio" name="fever" id="fever" value="1">
            </td>
            <td class="col-1">
                <input class="form-check-input" type="radio" name="fever" id="fever" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Ho <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="cough" id="cough" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="cough" id="cough" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Đau họng <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="sore_throat" id="sore_throat" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="sore_throat" id="sore_throat" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Khó thở <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="difficulty_of_breathing" id="difficulty_of_breathing" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="difficulty_of_breathing" id="difficulty_of_breathing" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Tiêu chảy <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="diarrhea" id="diarrhea" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="diarrhea" id="diarrhea" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Cảm thấy mệt mỏi <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="tired" id="tired" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="tired" id="tired" checked value="0">
            </td>
        </tr>
        <tr>
            <td>
                Mất mùi/Mất vị <span class="obligatory">(*)</span>
            </td>
            <td>
                <input class="form-check-input" type="radio" name="loss_taste" id="loss_taste" value="1">
            </td>
            <td>
                <input class="form-check-input" type="radio" name="loss_taste" id="loss_taste" checked value="0">
            </td>
        </tr>

    </tbody>
</table>
<table class="table table-bordered">
    <thead class="table-light">
    <tr>
        <th>Trong thời gian vừa qua</th>
        <th class="text-bold">Có</th>
        <th class="text-bold">Không</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="col-10">
            1. Bạn có đang mắc COVID-19 không? <span class="obligatory ">(*)</span>
        </td>
        <td class="col-1">
            <input class="form-check-input" type="radio" name="got_covid" id="got_covid" value="1">
        </td>
        <td class="col-1">
            <input class="form-check-input" type="radio" name="got_covid" id="got_covid" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            2. Bạn đã từng mắc COVID-19 không? <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="ever_had_covid" id="ever_had_covid" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="ever_had_covid" id="ever_had_covid" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            3. Tiếp xúc gần ca nhiễm, ca nghi nhiễm COVID-19 trong vòng 14 ngày qua
            <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="exposure_covid" id="exposure_covid" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="exposure_covid" id="exposure_covid" checked value="0">
        </td>
    </tr>
    <tr>
        <td>
            4. Bạn có kết thúc cách ly tập trung trong vòng 14 ngày qua không? (*) <span class="obligatory">(*)</span>
        </td>
        <td>
            <input class="form-check-input" type="radio" name="quarantined" id="quarantined" value="1">
        </td>
        <td>
            <input class="form-check-input" type="radio" name="quarantined" id="quarantined" checked value="0">
        </td>
    </tr>

    </tbody>
</table>
<div class="mb-3 ">
    <label for="address" class="form-label">Ghi chú</label>
    <textarea class="form-control" name="note" id="note" cols="" placeholder="Nhập ghi chú" rows="5"></textarea>
{{--                            <input type="text" class="form-control" name="address" id="address" aria-describedby="emailHelp">--}}
</div>
<div class="form-group{{ $errors->has('captcha') ? ' has-error' : '' }}">
    <label for="password" class="col-md-4 control-label py-2">Mã bảo mật<span
            class="obligatory">(*)</span></label>
    <div class="col-md-6 ">
        <div class="row">
            <div class="captcha col-sm-4">
                <span>{!! captcha_img() !!}</span>
                <button type="button" class="btn btn-success btn-refresh"><i class="fa fa-refresh"></i></button>
            </div>
            <div class="col-sm-8">
                <input id="captcha" type="text" class="form-control" placeholder="Nhập mã bảo mật" name="captcha">

            </div>

        </div>
        @if ($errors->has('captcha'))
            <span class="help-block">
          <strong>{{ $errors->first('captcha') }}</strong>
      </span>
        @endif
    </div>
</div>
<p class="text-danger py-4">Dữ liệu bạn cung cấp hoàn toàn bảo mật và chỉ phục vụ cho việc phòng chống dịch,
    thuộc quản lý của Ban chỉ đạo quốc gia về Phòng chống dịch Covid-19. Khi bạn nhấn nút "Gửi" là bạn đã
    hiểu và đồng ý.</p>
<div class="text-center">
    <a href="{{ route("user.declaration.index") }}" class="btn btn-info text-white">Quay lại</a>
    <button type="submit" class="btn btn-primary btn-submit btn-success">Gửi tờ khai</button>
</div>

resources/views/user/pages/declaration/declaration_myself.blade.php
@extends('user.layout.main',['title' => 'Khai báo y tế chi tiết'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Trang chủ</li>
                    <li class="breadcrumb-item">Khai báo y tế</li>
                    <li class="breadcrumb-item active" aria-current="page">Khai báo y tế cho bản thân</li>
                </ol>
            </nav>
            @include("user.shared._button-back")
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Khai báo y tế</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Thông tin khai báo cho bản thân</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    {{--                    @error('password')--}}
                    {{--                    <small class="text-danger">{{ $message }}</small>--}}
                    {{--                    @enderror--}}
                    <form action="{{ route('user.declaration.myself') }}" class="p-5" method="POST">
                        @csrf
                        @include('user.pages.declaration.declaration_detail')
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $(".btn-refresh").click(function(){
                $.ajax({
                    type:'GET',
                    url:'{{ route('user.refresh_captcha') }}',
                    success:function(data){
                        $(".captcha span").html(data.captcha);
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function(){
                $("#medical_station_id").attr('disabled', true);
                $("#ward").change(function(){
                    console.log($(this).val());
                    let id = $(this).val();
                    $.ajax({
                        url: '{{ route('medical-station.get') }}',
                        method:'POST',
                        data: {
                            id : id,
                            _token: '{{csrf_token()}}'
                        },
                        success: function (responsive){
                            console.log(responsive);
                            let medical_station_id = $("#medical_station_id");
                            medical_station_id.html(`<option value="0">-- Chọn trạm y tế --</option>`);
                            medical_station_id.attr('disabled', false);
                            $.each( responsive, function( key, value ) {
                                $("#medical_station_id").append(`<option value="${value['id']}">  ${value['name']} </option>`);
                            });

                        }
                    });
                });
            });
        </script>
    @endpush
@endsection

resources/views/user/pages/declaration/declaration_myself_edit.blade.php
@extends('user.layout.main',['title' => 'Cập nhật khai báo y tế'])
@section('content')
    <div class="content py-5">
        <div class="container-fluid">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Trang chủ</li>
                    <li class="breadcrumb-item">Khai báo y tế</li>
                    <li class="breadcrumb-item active" aria-current="page">Khai báo y tế cho người thân</li>
                </ol>
            </nav>
            @include("user.shared._button-back")
            <div id="module9" class="ModuleWrapper">
                <div id="wrapper9" class="passenger-wrapper">
                    <h1 class="text-center mtb-20">Cập nhật khai báo y tế</h1>
                </div>
                <div class="declaration-form px-2">
                    <div class="form_health_declaration">
                        <div class="title">
                            <div class="national-brand text-center mb-15">
                                <div class="text-uppercase">
                                    <b>Thông tin khai báo cho bản thân</b>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route('user.declaration.myself.edit', $declaration->object_id) }}" class="p-5" method="POST">
                        @csrf
                        @include('user.pages.declaration.declaration_detail_edit')
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $(".btn-refresh").click(function(){
                $.ajax({
                    type:'GET',
                    url:'{{ route('user.refresh_captcha') }}',
                    success:function(data){
                        $(".captcha span").html(data.captcha);
                    }
                });
            });
        </script>
    @endpush
@endsection